language: node_js

node_js:
  - "node"

script:
  npm i mobx --no-save && npm run src

# Recommended workaround for https://github.com/travis-ci/travis-ci/issues/8836
sudo: required
addons:
  chrome: stable
